spring:
  application:
    name: coupon-sale
  datasource:
    url: jdbc:mysql://localhost:3306/coupon_sell_system?createDatabaseIfNotExist=true
    username: root
    password: zawmyothantsin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
  servlet:
   multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  resources:
    static-locations: classpath:/static/, file:uploads/
cors:
  allowed-origin: http://localhost:4200
product:
  image:
    upload-dir: uploads/images

jwt:
  secret: ${SECRET-KEY}
